baseURL: "https://niladrik.github.io" 
title: Niladri Kal
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /research/
          weight: 2
        - name: Teaching
          url: /teaching/
          weight: 3
        - name: Contact
          url: contact/
          weight: 5 
        - name: Updates
          url: /news/
          weight: 4 

params:
    description: "Niladri's Homepage"
    author: Niladri Kal
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: auto
    hideNavbar: false
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","teaching","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Niladri Kal 
          subtitle: |
            <p style="margin-bottom:0.6rem; line-height:1.4;">Howdy! I am a Ph.D. student in the <a href="https://artsci.tamu.edu/statistics/index.html">Department of Statistics</a> at Texas A&M University, 
            advised by <a href="https://sites.google.com/view/rajguhaniyogi">Dr. Rajarshi Guhaniyogi</a> and <a href="https://pages.stat.wisc.edu/~dpati2/">Dr. Debdeep Pati</a>. Before joining A&M, 
            I earned my master’s from the <a href="https://www.isical.ac.in">Indian Statistical Institute</a> and my bachelor's from <a href="https://www.sxccal.edu/">St. Xavier’s College (Autonomous), Kolkata</a>.</p>
            
            <p style="margin-bottom:0rem; line-height:1.4;">My current research focuses on scalable Bayesian methodologies for federated setups and on high-dimensional structured modeling. 
            In my spare time, I enjoy playing the piano, chasing the perfect light with my camera, and a quiet cup of chai.</p>
                                
          imageUrl: "/ProfileNew.png"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: Research
              url: /research/
            - name: Teaching
              url: /teaching/
            - name: Updates
              url: /news/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:niladrik@tamu.edu
        - name: Location
          url: contact/
        - name: GitHub
          url: https://github.com/niladrik
        - name: X
          url: https://x.com/kalniladri
        - name: LinkedIn
          url: https://www.linkedin.com/in/niladrikal

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Niladri Kal | নীলাদ্রি কাল"
      icon: tamu-favicon.png
      iconHeight: 18

    customCSS:
        - css/extended/custom.css

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
